# Generated by Django 4.1.4 on 2023-01-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="descriptiom",
            new_name="description",
        ),
    ]
